const express = require('express');
const fetch = require('node-fetch');
const router = express.Router();

const GITHUB_API = 'https://api.github.com';

function getHeaders() {
  return {
    'Authorization': `Bearer ${process.env.GITHUB_TOKEN}`,
    'Accept': 'application/vnd.github+json',
    'X-GitHub-Api-Version': '2022-11-28',
    'Content-Type': 'application/json',
  };
}

function getOrg() {
  return process.env.GITHUB_ORG || 'askboppana';
}

// The consumer CI template content
function getCiTemplate(stack, orgName) {
  const workflowMap = {
    java:       '_deploy.yml',
    javascript: '_deploy.yml',
    python:     '_deploy.yml',
    dotnet:     '_deploy.yml',
    uipath:     '_deploy.yml',
    salesforce: '_deploy.yml',
    default:    '_deploy.yml',
  };

  const workflow = workflowMap[stack] || workflowMap.default;

  return `# ForgeOps CI/CD Pipeline
# Auto-generated by ForgeOps onboarding
# Triggers on push to feature branches and PRs to environment branches
name: CI/CD

on:
  push:
    branches: ['feature/*', 'hotfix/*']
  pull_request:
    branches: [int, qa, stage, main]
    types: [closed]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment'
        required: true
        type: choice
        options: [int, qa, stage, prod]

jobs:
  pipeline:
    uses: ${orgName}/ForgeOps/.github/workflows/${workflow}@main
    with:
      app_name: \${{ github.event.repository.name }}
      version: \${{ github.sha }}
      environment: \${{ github.event_name == 'workflow_dispatch' && github.event.inputs.environment || 'int' }}
    secrets: inherit
`;
}

// POST /api/onboarding/add-ci — add CI template to a single repo
router.post('/add-ci', async (req, res) => {
  try {
    const { owner, repo, stack } = req.body;
    const org = owner || getOrg();
    const template = getCiTemplate(stack || 'default', org);
    const content = Buffer.from(template).toString('base64');

    console.log(`Onboarding: adding ci.yml to ${org}/${repo}`);

    // Check if file already exists
    const checkRes = await fetch(
      `${GITHUB_API}/repos/${org}/${repo}/contents/.github/workflows/ci.yml`,
      { headers: getHeaders() }
    );

    if (checkRes.status === 200) {
      const existing = await checkRes.json();
      return res.json({
        status: 'exists',
        message: `${repo} already has .github/workflows/ci.yml`,
        sha: existing.sha,
      });
    }

    // Create the file
    const createRes = await fetch(
      `${GITHUB_API}/repos/${org}/${repo}/contents/.github/workflows/ci.yml`,
      {
        method: 'PUT',
        headers: getHeaders(),
        body: JSON.stringify({
          message: 'chore: add ForgeOps CI/CD pipeline [skip ci]',
          content: content,
        }),
      }
    );

    const data = await createRes.json();

    if (createRes.status === 201) {
      console.log(`Onboarded: ${org}/${repo}`);
      res.json({
        status: 'created',
        message: `CI template added to ${repo}`,
        sha: data.content?.sha,
        url: data.content?.html_url,
      });
    } else {
      console.error(`Onboard failed for ${repo}:`, createRes.status, data.message);
      res.status(createRes.status).json({
        status: 'error',
        message: data.message || 'Failed to create file',
      });
    }
  } catch (err) {
    console.error('Onboarding error:', err);
    res.status(500).json({ status: 'error', message: err.message });
  }
});

// POST /api/onboarding/bulk — onboard multiple repos at once
router.post('/bulk', async (req, res) => {
  try {
    const { repos, stack } = req.body;  // repos = [{owner, name}]
    if (!Array.isArray(repos) || repos.length === 0) {
      return res.status(400).json({ error: 'repos array required' });
    }

    const org = getOrg();
    const results = [];

    for (const r of repos) {
      const repoName = r.name || r;
      const repoOwner = r.owner || org;

      try {
        const template = getCiTemplate(stack || r.stack || 'default', repoOwner);
        const content = Buffer.from(template).toString('base64');

        // Check if exists
        const checkRes = await fetch(
          `${GITHUB_API}/repos/${repoOwner}/${repoName}/contents/.github/workflows/ci.yml`,
          { headers: getHeaders() }
        );

        if (checkRes.status === 200) {
          results.push({ repo: repoName, status: 'skipped', message: 'Already has ci.yml' });
          continue;
        }

        // Create
        const createRes = await fetch(
          `${GITHUB_API}/repos/${repoOwner}/${repoName}/contents/.github/workflows/ci.yml`,
          {
            method: 'PUT',
            headers: getHeaders(),
            body: JSON.stringify({
              message: 'chore: add ForgeOps CI/CD pipeline [skip ci]',
              content: content,
            }),
          }
        );

        if (createRes.status === 201) {
          results.push({ repo: repoName, status: 'created', message: 'CI template added' });
        } else {
          const err = await createRes.json();
          results.push({ repo: repoName, status: 'error', message: err.message || `HTTP ${createRes.status}` });
        }
      } catch (err) {
        results.push({ repo: repoName, status: 'error', message: err.message });
      }

      // Small delay to avoid rate limiting
      await new Promise(resolve => setTimeout(resolve, 200));
    }

    const created = results.filter(r => r.status === 'created').length;
    const skipped = results.filter(r => r.status === 'skipped').length;
    const errors = results.filter(r => r.status === 'error').length;

    console.log(`Bulk onboard: ${created} created, ${skipped} skipped, ${errors} errors out of ${repos.length}`);

    res.json({
      summary: { total: repos.length, created, skipped, errors },
      results,
    });
  } catch (err) {
    console.error('Bulk onboarding error:', err);
    res.status(500).json({ error: err.message });
  }
});

// GET /api/onboarding/template — get the CI template content
router.get('/template', (req, res) => {
  const stack = req.query.stack || 'default';
  const org = req.query.org || getOrg();
  res.json({
    filename: '.github/workflows/ci.yml',
    content: getCiTemplate(stack, org),
    stack,
  });
});

module.exports = router;
